# Generated by Django 4.1.3 on 2022-12-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_alter_team_id"),
        ("projects", "0002_project_team"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="team",),
        migrations.AddField(
            model_name="project",
            name="team",
            field=models.ManyToManyField(to="teams.team"),
        ),
    ]
