# Generated by Django 4.1.3 on 2022-12-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_remove_project_team_project_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="client_name",
            field=models.CharField(
                blank=True, db_index=True, max_length=256, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
