# Generated by Django 4.1.4 on 2023-01-10 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0005_invitation"),
        ("projects", "0004_project_client_name_project_due_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="team",),
        migrations.AddField(
            model_name="project",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="teams.team",
            ),
        ),
    ]
