# Generated by Django 4.1.3 on 2022-12-21 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0002_remove_scripts_project_scripts_product"),
    ]

    operations = [
        migrations.RemoveField(model_name="scripts", name="description",),
    ]
