# Generated by Django 4.1.3 on 2022-12-21 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0003_remove_scripts_description"),
    ]

    operations = [
        migrations.RemoveField(model_name="scripts", name="script_name",),
    ]
