# Generated by Django 4.1.3 on 2022-12-21 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scripts", "0004_remove_scripts_script_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpdateScriptInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_date", models.DateTimeField(auto_now_add=True)),
                (
                    "scripts",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scripts.scripts",
                    ),
                ),
                (
                    "updated_author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
