# Generated by Django 4.1.4 on 2022-12-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scripts", "0006_scriptcomment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scriptcomment", old_name="post", new_name="script",
        ),
    ]
