# Generated by Django 4.1.3 on 2022-11-27 05:58

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import hitcount.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("taggit", "0004_alter_taggeditem_content_type_alter_taggeditem_tag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("slug", models.SlugField(max_length=250, unique_for_date="publish")),
                ("image", models.ImageField(upload_to="featured_image/%Y/%m/%d/")),
                ("body", ckeditor_uploader.fields.RichTextUploadingField()),
                ("publish", models.DateTimeField(default=django.utils.timezone.now)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("category", models.CharField(default="uncategorized", max_length=250)),
                ("thumbsup", models.IntegerField(default="0")),
                ("thumbsdown", models.IntegerField(default="0")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("hidden", "Hidden"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("read_time", models.IntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "favourites",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        related_name="favourite",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "thumbs",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        related_name="thumbs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ("-publish",),},
            bases=(models.Model, hitcount.models.HitCountMixin),
            managers=[("newmanager", django.db.models.manager.Manager()),],
        ),
    ]
