# Generated by Django 4.1.4 on 2022-12-30 13:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0004_remove_product_model_remove_product_scripts"),
    ]

    operations = [
        migrations.CreateModel(
            name="endPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "endpoint_file",
                    models.FileField(
                        blank=True, null=True, upload_to="endpoint/%Y/%m/%d/"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
        ),
    ]
