# Generated by Django 4.1.3 on 2022-12-03 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailnotification",
            old_name="interesteed_blog_update",
            new_name="interested_blog_update",
        ),
    ]
