# Generated by Django 4.1.3 on 2022-11-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="account_type",
            field=models.CharField(db_index=True, default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="address1",
            field=models.CharField(db_index=True, default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="address2",
            field=models.CharField(db_index=True, default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="banner_pic",
            field=models.ImageField(default=1, upload_to="banner_pic/%Y/%m/%d/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(db_index=True, default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="country",
            field=models.CharField(db_index=True, default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(db_index=True, default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(default=1, upload_to="profile_pic/%Y/%m/%d/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_privacy",
            field=models.CharField(db_index=True, default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="state",
            field=models.CharField(db_index=True, default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="zip_code",
            field=models.CharField(db_index=True, default=1, max_length=256),
            preserve_default=False,
        ),
    ]
