# Generated by Django 4.1.3 on 2022-11-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_account_type_profile_address1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_privacy",
            field=models.CharField(db_index=True, default="anyone", max_length=25),
        ),
    ]
