# Generated by Django 4.1.4 on 2023-01-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_billing_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="paypal_email",
            field=models.EmailField(blank=True, db_index=True, max_length=255),
        ),
    ]
