# Generated by Django 4.1.4 on 2023-01-05 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="API",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("api", models.CharField(db_index=True, max_length=256)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                ("enddate", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
