# Generated by Django 4.1.4 on 2023-01-05 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0005_invitation"),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="api",
            name="team",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="teams.team"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="api",
            name="active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="api",
            name="enddate",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
