# Generated by Django 4.1.4 on 2023-01-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_apilog_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apilog", options={"ordering": ("-created_date",)},
        ),
        migrations.AlterField(
            model_name="apilog",
            name="price",
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
    ]
