# Generated by Django 4.1.4 on 2023-01-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0002_customer_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="plan",
            field=models.CharField(db_index=True, default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customer",
            name="cancel_at_period_end",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="customer",
            name="membership",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
