# Generated by Django 4.1.4 on 2023-01-09 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "membership",
            "0003_customer_plan_alter_customer_cancel_at_period_end_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(model_name="customer", name="plan",),
    ]
