# Generated by Django 4.1.3 on 2022-12-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price_per_request",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
