# Generated by Django 4.1.3 on 2022-12-18 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0001_initial"),
        ("scripts", "0001_initial"),
        ("product", "0002_alter_product_price_per_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="model.model",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="scripts",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scripts.scripts",
            ),
        ),
    ]
