# Generated by Django 4.1.3 on 2022-12-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_product_model_alter_product_scripts"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="model",),
        migrations.RemoveField(model_name="product", name="scripts",),
    ]
