# Generated by Django 4.1.4 on 2023-01-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_product_manual_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="index",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                db_index=True,
                default="public",
                max_length=10,
            ),
        ),
    ]
