# Generated by Django 4.1.4 on 2023-01-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_product_index_product_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price_per_request",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
