# Generated by Django 4.1.4 on 2022-12-30 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fields", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="fields", name="model",),
        migrations.RemoveField(model_name="fields", name="project",),
    ]
