# Generated by Django 4.1.4 on 2023-01-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fields", "0002_remove_fields_model_remove_fields_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="fields",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("string", "string"),
                    ("integer", "integer"),
                    ("float", "float"),
                ],
                default="string",
                max_length=20,
            ),
        ),
    ]
