# Generated by Django 4.1.3 on 2022-12-20 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_product_model_alter_product_scripts"),
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="files",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
            ),
            preserve_default=False,
        ),
    ]
