# Generated by Django 4.1.3 on 2022-12-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_files_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="files",
            name="script_name",
            field=models.CharField(db_index=True, default=1, max_length=254),
            preserve_default=False,
        ),
    ]
