# Generated by Django 4.1.3 on 2022-12-21 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("files", "0003_files_script_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="files", name="updated_date",),
        migrations.AddField(
            model_name="files",
            name="script_code",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="UpdateFileInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_date", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
