# Generated by Django 4.1.3 on 2022-12-21 05:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0005_files_updated_date_updatefileinfo_files_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="files",
            name="script_code",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
