# Generated by Django 4.1.3 on 2022-12-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0006_alter_files_script_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="files", name="script_code", field=models.TextField(),
        ),
    ]
