# Generated by Django 4.1.4 on 2023-01-23 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_remove_project_team_project_team"),
        ("files", "0007_alter_files_script_code"),
    ]

    operations = [
        migrations.RemoveField(model_name="files", name="product",),
        migrations.AddField(
            model_name="files",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
            ),
            preserve_default=False,
        ),
    ]
