# Generated by Django 4.1.3 on 2022-12-21 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_remove_product_model_remove_product_scripts"),
        ("model", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="model", name="project",),
        migrations.AddField(
            model_name="model",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
            ),
            preserve_default=False,
        ),
    ]
