# Generated by Django 4.1.3 on 2022-12-03 16:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teams", "0002_team_description"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="team", unique_together={("title", "created_by")},
        ),
    ]
