# Generated by Django 4.1.3 on 2022-12-03 17:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_alter_team_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
