# Generated by Django 4.1.3 on 2022-11-26 06:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(db_index=True, max_length=256)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("phone", models.CharField(db_index=True, max_length=15)),
                ("detail", models.TextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
